services:
    aidbox:
        image: healthsamurai/aidboxone:stable
        depends_on:
            - aidbox-db
        links:
            - 'aidbox-db:database'
        ports:
            - '127.0.0.1:8080:8080'
        env_file:
            - ./env/aidbox
            - .env
        volumes:
            - ./zenproject:/zenproject
    aidbox-db:
        image: 'healthsamurai/aidboxdb:13.2'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: aidbox
    aidbox-healthcheck:
        image: curlimages/curl
        entrypoint: /bin/sleep 10000
        links:
            - aidbox
        depends_on:
            - aidbox
        healthcheck:
            test: curl --fail http://aidbox:8080/health || exit 1
            interval: 5s
            timeout: 30s
            retries: 100
    nginx:
      image: jonasal/nginx-certbot
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - ./letsencrypt:/etc/letsencrypt
      environment:
        CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      depends_on:
        aidbox-healthcheck:
          condition:
            service_healthy
      profiles: ["production"]
