services:
    aidbox:
        image: healthsamurai/aidboxone:stable
        depends_on:
            - aidbox-db
            - build-seeds
        links:
            - 'aidbox-db:database'
        ports:
            - '127.0.0.1:8080:8080'
        env_file:
            - ./env/aidbox
            - .env
        volumes:
            - ./zenproject:/zenproject
    aidbox-db:
        image: 'healthsamurai/aidboxdb:13.2'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: aidbox
    aidbox-healthcheck:
        image: curlimages/curl
        entrypoint: /bin/sleep 10000
        links:
            - aidbox
        depends_on:
            - aidbox
        healthcheck:
            test: curl --fail http://aidbox:8080/health || exit 1
            interval: 5s
            timeout: 30s
            retries: 100
    build-seeds:
        build:
            context: .
            dockerfile: Dockerfile.seeds
        volumes:
            - ./zenproject:/app/zenproject
            - ./resources/seeds:/app/resources/seeds
    nginx:
      image: jonasal/nginx-certbot
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./assets:/www/assets:ro
      environment:
        CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      depends_on:
        aidbox-healthcheck:
          condition:
            service_healthy
      profiles: ["production"]
    smart-app-deps:
      image: node:18
      command: bash -c "cd /app && npm install"
      volumes:
      - ./smart:/app
      profiles: ["smart-app"]
    smart-app:
      build: ./smart
      env_file:
          - .env
      command: npm run dev
      ports: 
      - "5173:5173"
      volumes:
      - ./smart:/app
      depends_on:
        smart-app-deps:
          condition: service_completed_successfully
      profiles: ["smart-app"]
    client:
      build: ./client
      ports:
      - "8888:8888"
      volumes:
      - ./client:/app
      profiles: ["client"]
    matchbox:
      image: eu.gcr.io/fhir-ch/matchbox:v314
      profiles: ["production"]
    smart-form-ide:
      image: ghcr.io/beda-software/smart-form-ide:latest
      profiles: ["production"]
    smile-emr:
      image: registry.beda.software/emr/smile-digital-health-demo:latest
      profiles: ["production"]
    aups:
      image: ghcr.io/beda-software/au-ps-summary-op:33751833af188b78dda7bc16901888d4534f1828
      env_file:
            - ./env/aups
      depends_on:
        aidbox-healthcheck:
          condition:
            service_healthy
    

