name: Deploy Aidbox with AU Core profile
on:
  workflow_dispatch:
  push:
    branches:
      - services-only
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Generate .env and restart
        uses: appleboy/ssh-action@v0.1.7
        env:
          AIDBOX_LICENSE: ${{secrets.AIDBOX_LICENSE}}
          CERTBOT_EMAIL: ${{secrets.CERTBOT_EMAIL}}
          APP_INIT_CLIENT_SECRET: ${{secrets.APP_INIT_CLIENT_SECRET}}
          APP_SECRET: ${{secrets.APP_SECRET}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.PRIVATE_KEY}}
          envs: >
            AIDBOX_LICENSE,CERTBOT_EMAIL,
            APP_INIT_CLIENT_SECRET,APP_SECRET,
            AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,
            OPENAI_API_KEY
          script_stop: true
          script: |
            cd ~/au-core-aidbox
            git pull
            echo "AIDBOX_LICENSE=$AIDBOX_LICENSE" > .env
            echo "BOX_FEATURES_FTR_PULL_ENABLE=true" >> .env
            echo "AIDBOX_BASE_URL=https://au-core.beda.software" >> .env
            echo "AIDBOX_ZEN_DEV_MODE=disable" >> .env
            echo "CERTBOT_EMAIL=$CERTBOT_EMAIL" >> .env
            echo "APP_INIT_CLIENT_SECRET=$APP_INIT_CLIENT_SECRET" >> .env
            echo "APP_SECRET=$APP_SECRET" >> .env
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
            echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
            make restart_production
