name: Deploy EMR and SDC-IDE configs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Generate .env and restart
        uses: appleboy/ssh-action@v0.1.7
        env:
          AIDBOX_LICENSE: ${{secrets.AIDBOX_LICENSE}}
          CERTBOT_EMAIL: ${{secrets.CERTBOT_EMAIL}}
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.PRIVATE_KEY}}
          envs: >
            AIDBOX_LICENSE,CERTBOT_EMAIL
          script_stop: true
          script: |
            cd ~/au-core-aidbox
            echo "AIDBOX_LICENSE=$AIDBOX_LICENSE" > .env
            echo "BOX_FEATURES_FTR_PULL_ENABLE=true" >> .env
            docker compose pull -q
            docker compose stop
            docekr compose up -d
